### ISSUE TITLE
Any page on oaf.org.au with comments is badly broken

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/oaf#337]
See for example https://www.oaf.org.au/2020/09/29/the-story-of-a-tiny-almost-invisible-change/

The problem is due to the upgrade to php 7.4 and thematic which is still using ereg() which is not supported in php 7.4. 😢

**Comment by mlandauer** [comment]
I'm going to try to work on this now

**Comment by mlandauer** [comment]
This is an example error in `/var/log/apache2/error.log`
```
[Mon Mar 14 11:55:59.074218 2022] [php7:error] [pid 6224] [client 180.150.11.131:43500] PHP Fatal error:  Uncaught Error: Call to undefined function ereg() in /var/www/html/wp-content/themes/thematic/library/extensions/comments-extensions.php:262
Stack trace:
#0 /var/www/html/wp-content/themes/thematic/library/extensions/discussion.php(30): thematic_commenter_link()
#1 /var/www/html/wp-includes/class-walker-comment.php(184): thematic_comments()
#2 /var/www/html/wp-includes/class-wp-walker.php(146): Walker_Comment->start_el()
#3 /var/www/html/wp-includes/class-walker-comment.php(139): Walker->display_element()
#4 /var/www/html/wp-includes/class-wp-walker.php(389): Walker_Comment->display_element()
#5 /var/www/html/wp-includes/comment-template.php(2250): Walker->paged_walk()
#6 /var/www/html/wp-content/themes/thematic/comments.php(80): wp_list_comments()
#7 /var/www/html/wp-includes/comment-template.php(1556): require('/var/www/html/w...')
#8 /var/www/html/wp-content/themes/thematic/library/extensions/comments-extensions.php(291): comments_template()
#9 /var/www/html/wp-includes/class-wp-hook.php(307): thematic_inc in /var/www/html/wp-content/themes/thematic/library/extensions/comments-extensions.php on line 262, referer: https://www.oaf.org.au/wp-admin/edit-comments.php
```
